name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec rake build

      - name: Download rcedit
        run: |
          Invoke-WebRequest -Uri "https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe" -OutFile "rcedit.exe"

      - name: Fix embedded icon
        run: .\rcedit.exe dist\ppap.exe --set-icon ppap.ico

      - uses: actions/upload-artifact@v4
        with:
          name: ppap
          path: dist/*
