name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build executable
        run: bundle exec rake build

      - name: Create ZIP package
        shell: pwsh
        run: |
          $dir = Join-Path "dist" "ppap-${{ github.ref_name }}"
          $zip = Join-Path "dist" "ppap-${{ github.ref_name }}-windows-x64.zip"
          $files = @(
            "dist\ppap.exe",
            "LICENSE",
            "README.md"
          )
          Remove-Item -Path $dir -Recurse -Force -ErrorAction Ignore
          Remove-Item -Path $zip -Force -ErrorAction Ignore
          New-Item -Path $dir -ItemType Directory | Out-Null
          foreach ($file in $files) {
            Copy-Item -Path $file -Destination (Join-Path $dir (Split-Path $file -Leaf))
          }
          Compress-Archive `
            -Path $dir `
            -DestinationPath $zip

      - name: Generate SHA256
        shell: pwsh
        run: |
          @(
            "dist/ppap.exe",
            "dist/ppap-${{ github.ref_name }}-windows-x64.zip"
          ) |
          ForEach-Object {
            $hash = (Get-FileHash $_ -Algorithm SHA256).Hash.ToLower()
            "$hash *$(Split-Path $_ -Leaf)"
          } |
          Set-Content "dist/SHA256SUMS.txt"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/ppap.exe
            dist/ppap-${{ github.ref_name }}-windows-x64.zip
            dist/SHA256SUMS.txt
